'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''updatepnl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatepnl As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnGetTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetTemplate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnImportExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImportExcel As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''loadFileSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loadFileSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''fuOPenEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuOPenEx As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AddFilesSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddFilesSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''fuAddClaimFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuAddClaimFile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnSaveFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveFile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBackFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackFile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblText1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblText1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPageSize As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblText2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblText2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExcel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPdf As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCopy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''notVisibleKeyPress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notVisibleKeyPress As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rdCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdCustomer As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdPartNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdPartNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdDate As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdClaimNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdClaimNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdStatusOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdStatusOut As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdStatusIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdStatusIn As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdUser As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''convert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents convert As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblTotalClaims control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalClaims As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtClaimNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaimNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDateInit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateInit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlSearchReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchReason As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSearchDiagnose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchDiagnose As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSearchExtStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchExtStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSearchIntStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchIntStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSearchUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchUser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlClaimType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlClaimType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hiddenId1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenId1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenId2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenId2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdClaimNoSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdClaimNoSelected As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdPartNoSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdPartNoSelected As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdCustomerNoSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCustomerNoSelected As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdDateInitSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdDateInitSelected As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdLinkExpand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdLinkExpand As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdTriggeredControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdTriggeredControl As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdLaunchControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdLaunchControl As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdSelectedClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdSelectedClass As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdFileImportFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdFileImportFlag As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdAddClaimFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdAddClaimFile As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdShowTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdShowTemplate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdReason As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdDiagnose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdDiagnose As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdStatusOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdStatusOut As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''selectedFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedFilter As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ndtt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ndtt As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblGrvGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGrvGroup As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdGridViewContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdGridViewContent As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdNavTabsContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdNavTabsContent As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdComments As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdFlagUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdFlagUpload As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdFlagUploadTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdFlagUploadTxt As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdmhstde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdmhstde As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdflgoth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdflgoth As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdmhwtyp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdmhwtyp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdmhwrea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdmhwrea As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdcwstde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdcwstde As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdcwdiagd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdcwdiagd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdcmbtxtdiag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdcmbtxtdiag As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdCLMemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCLMemail As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdCLMuser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCLMuser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdCLMLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCLMLimit As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdUsrLimitAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdUsrLimitAmt As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdSwLimitAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdSwLimitAmt As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdCurrentActiveTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCurrentActiveTab As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdSeq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdSeq As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdlastComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdlastComment As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''chkinitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkinitial As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdWkStatOne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdWkStatOne As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdWkStatTwo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdWkStatTwo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdSelectedDiagnose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdSelectedDiagnose As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdLocationSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdLocationSelected As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdVendorClaimNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdVendorClaimNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdDisplaySeeVndClaim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdDisplaySeeVndClaim As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdDisplayAddVndClaim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdDisplayAddVndClaim As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdSeeVndComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdSeeVndComments As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdSeeComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdSeeComments As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdAddVndComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdAddVndComments As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdAddComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdAddComments As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''addProdDev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addProdDev As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblWhlCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWhlCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWhlCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWhlCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCreationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreationDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCreationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreationDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCurrentVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentVendor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCurrentVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurrentVendor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDescriptionPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescriptionPD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDescriptionPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescriptionPD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCreateProjectPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateProjectPD As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPDBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPDBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gridviewRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridviewRow As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grvClaimReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvClaimReport As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''navsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navsSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFirstTabDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstTabDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnISDet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnISDet As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblClaimNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClaimNoData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtClaimNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaimNoData As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblClaimType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClaimType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtClaimType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaimType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPartNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPartNoData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPartNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartNoData As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnChangePart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChangePart As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPartDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPartDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPartDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEnteredBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnteredBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEnteredBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnteredBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDateEntered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateEntered As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDateEntered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateEntered As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblUnitCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnitCost As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtUnitCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInvoiceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtInvoiceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInvoiceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtInvoiceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEnteredFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnteredFrom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEnteredFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnteredFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLocation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblInstDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInstDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtInstDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInstDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblHWorked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHWorked As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtHWorked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHWorked As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCustStatement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustStatement As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCustStatement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustStatement As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnContact As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCustomerData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCustomerData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerData As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblContactName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtContactName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblContactPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactPhone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtContactPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblContactEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtContactEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnInformation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSerial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSerial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblArrangement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArrangement As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtArrangement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArrangement As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblModel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModel1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtModel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModel1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSerial1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSerial1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSerial1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSerial1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblArrangement1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArrangement1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtArrangement1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArrangement1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSecondTabDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecondTabDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnClaimsDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnClaimsDept As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblQuarantine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuarantine As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkQuarantine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkQuarantine As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtQuarantine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuarantine As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQuarantineDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuarantineDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDiagnose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiagnose As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDiagnoseData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiagnoseData As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlDiagnoseData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDiagnoseData As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblClaimReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClaimReason As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtClaimReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaimReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblProductionCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductionCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtProductionCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductionCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblVendorNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVendorNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVendorNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnChangeVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChangeVendor As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblVendorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendorName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVendorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVendorName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInvoiceNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceNo1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtInvoiceNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceNo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInvoiceDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceDate1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtInvoiceDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceDate1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBarSeq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBarSeq As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBarSeq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBarSeq As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblReceiving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReceiving As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtReceiving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceiving As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnPartImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnPartImage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''datViewer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datViewer As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''txtPartDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnSalesDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnSalesDept As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblClaimAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClaimAuth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkClaimAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkClaimAuth As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtClaimAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaimAuth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtClaimAuthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaimAuthDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAmountApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmountApproved As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAmountApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountApproved As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnRestock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnRestock As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnRestock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRestock As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUndoRestock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUndoRestock As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblThirdTabDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblThirdTabDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnInternalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnInternalStatus As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblActualStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActualStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtActualStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActualStatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInitialReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInitialReview As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkInitialReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInitialReview As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtInitialReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInitialReview As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtInitialReviewDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInitialReviewDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAcknowledgeEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAcknowledgeEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkAcknowledgeEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAcknowledgeEmail As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAcknowledgeEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcknowledgeEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAcknowledgeEmailDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcknowledgeEmailDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInfoCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoCust As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkInfoCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInfoCust As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtInfoCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInfoCust As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtInfoCustDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInfoCustDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPartRequested control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPartRequested As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkPartRequested control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPartRequested As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtPartRequested control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartRequested As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartRequestedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartRequestedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPartReceived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPartReceived As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkPartReceived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPartReceived As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtPartReceived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartReceived As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartReceivedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTechReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTechReview As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkTechReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTechReview As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtTechReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTechReview As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTechReviewDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTechReviewDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWaitSupReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWaitSupReview As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkWaitSupReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWaitSupReview As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtWaitSupReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWaitSupReview As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWaitSupReviewDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWaitSupReviewDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblClaimCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClaimCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkClaimCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkClaimCompleted As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtClaimCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaimCompleted As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtClaimCompletedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaimCompletedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnTotals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnTotals As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnSubTotalClaimed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnSubTotalClaimed As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblParts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParts As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtParts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParts As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFreight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFreight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFreight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnConsequentalDamage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnConsequentalDamage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkConsDamage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkConsDamage As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblConsDamage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConsDamage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCDLabor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCDLabor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCDLabor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCDLabor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCDPart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCDPart As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCDPart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCDPart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCDFreight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCDFreight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCDFreight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCDFreight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCDMisc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCDMisc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCDMisc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCDMisc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtConsDamageTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsDamageTotal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnSubTotalClaim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnSubTotalClaim As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApproved As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkApproved As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblDeclined control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeclined As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkDeclined control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDeclined As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnExternalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnExternalStatus As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblClaimStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClaimStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtClaimStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaimStatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTotalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnActions As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnSubActionFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnSubActionFiles As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnAddFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddFiles As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSeeFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSeeFiles As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnSubActionFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnSubActionFinal As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnPurchasing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPurchasing As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCloseClaim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseClaim As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblFourTabDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFourTabDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnSubActionComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnSubActionComment As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnAddComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddComments As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSeeComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSeeComments As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rowAddComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowAddComments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''addCommentsR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addCommentsR As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnClaimComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnClaimComm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAddWrnNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddWrnNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAddWrnNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddWrnNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAddRetNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddRetNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAddRetNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddRetNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddCommDateInit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddCommDateInit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddCommDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddCommDateTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAddSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddSubject As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAddSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddSubject As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAddIntComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddIntComm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rdAddIntComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdAddIntComm As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblAddExtComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddExtComm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rdAddExtComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdAddExtComm As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''grvAddComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvAddComm As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''addVendorComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addVendorComments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAddClaimNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddClaimNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAddClaimNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddClaimNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddVndCommDateInit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddVndCommDateInit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddVndCommDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddVndCommDateTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAddVndSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddVndSubject As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAddVndSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddVndSubject As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rowSeeComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSeeComments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''seeCommentsR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents seeCommentsR As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblWrnNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWrnNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWrnNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWrnNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRetNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRetNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRetNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRetNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''grvSeeComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvSeeComm As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''seeVendorComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents seeVendorComments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSeeVndComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeeVndComm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSeeVndComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSeeVndComm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''grvSeeVndComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvSeeVndComm As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnPrintSeeVndClaim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintSeeVndClaim As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExitSeeVndClaim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExitSeeVndClaim As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rowBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowBtn As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNew As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSaveTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveTab As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnCloseTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseTab As Global.System.Web.UI.WebControls.LinkButton
End Class
